### PR TITLE
Hide GlobalInstance in one translation unit

### PR DESCRIPTION
**Pull request by seanm**
Provide a getter for retrieving the singleton.

### CODE REVIEW

**Comment by seanm** [comment]
@malaterre

**Comment by malaterre** [comment]
i am pretty sure this won't work

**Comment by seanm** [comment]
Why does each translation unit need its own instance?

**Comment by malaterre** [comment]
Well this is a standard construct. I can see it in use here:
 
* https://www.vtk.org/gitweb?p=VTK.git;a=blob;f=Common/Core/vtkDebugLeaksManager.h;h=028b27f17c2fe4b0ea54d77f7da39c8545256a49;hb=HEAD

**Pull request closed without merging**
