### PR TITLE
Change method to compute inter slice value in RetrieveSOPInstanceUIDFromZPosition

### PR DESCRIPTION
**Pull request by tbaudier**
Previously, the inter slice value was based on SpacingBetweenSlice tag.
But prefer to compute inter slice value from the difference of z positions of the 2 first slices.
Extracted from https://stackoverflow.com/questions/37730772/get-distance-between-slices-in-dicom/41848360#41848360

Follow https://github.com/malaterre/GDCM/pull/125

### CODE REVIEW

**Comment by malaterre** [comment]
I do not strong opinion on this patch, but I would suggest you centralize the implementation. Technically one should be able to re-use existing implementation from gdcmIPPSorter.h, right ?

**Comment by tbaudier** [comment]
I saw the implementation in gdcmIPPSorter class but from the filenames and not the DataSet. Firstly, this is why I decided to do it like that.
I just try to use the implementation available in gdcmIPPSorter. You can find the commit here:
https://github.com/tbaudier/GDCM/commit/53b7727258e1119022b7ec0a03669b5b87ef5989
In that case I needed to modify RetrieveSOPInstanceUIDFromZPosition arguments. I do not know which strategy is preferable.

If you have other idea, I can try to implement it.
Thank you

**Comment by malaterre** [comment]
Well the API from DirectoryHelper::RetrieveSOPInstanceUIDFromZPosition has always bugged me. Technically you never need to load the whole world to do the computation. Instead of accepting a vector<DataSet> it should instead take a gdcm::Scanner properly setup with the minimal set of tag.

Are you a heavy user of vtkGDCMPolyDataWriter ? Very few people actually uses gdcm::DirectoryHelper

**Comment by tbaudier** [comment]
> Well the API from `DirectoryHelper::RetrieveSOPInstanceUIDFromZPosition` has always bugged me. Technically you never need to load the whole world to do the computation. Instead of accepting a `vector<DataSet>` it should instead take a `gdcm::Scanner` properly setup with the minimal set of tag.

`vtkGDCMPolyDataWriter` should initialize a `gdcm::Scanner` but I do not know if it's feasible or not.

> 
> Are you a heavy user of `vtkGDCMPolyDataWriter` ? Very few people actually uses `gdcm::DirectoryHelper`

We use `vtkGDCMPolyDataWriter` a lot to convert our binary mask image (mhd format) to dicom RTStruct (https://github.com/open-vv/vv/blob/master/common/clitkImage2DicomRTStructFilter.txx#L122). This method is very useful for us.

**Comment by malaterre** [comment]
Change is bit too big for me. Let me have another look at gdcmIPPSorter to see if there is some possible refactor.

**Comment by tbaudier** [comment]
Thank you very much, do not hesitate if you want some help

**Pull request merged**
