### PR TITLE
Fixed many cmake 3.20rc4 warnings about policy CMP0115

### PR DESCRIPTION
**Pull request by seanm**
Just added filename extensions to various references files.

### CODE REVIEW

**Comment by seanm** [comment]
@malaterre this change is analogous to how these CMP0115 warnings were fixed in VTK and ITK, and while it fixes them for GDCM too, it causes all tests to fail with messages like `TestVersion.cxx is an invalid test name`.

So I'm not sure what to do...

**Comment by seanm** [comment]
@malaterre friendly ping...

**Comment by malaterre** [comment]
@seanm what do you mean by 👍 

> it causes all tests to fail with messages like TestVersion.cxx is an invalid test name.

I cannot merge something which will break testing...

**Comment by seanm** [comment]
>I cannot merge something which will break testing...

Of course!

This patch is more of a WIP I guess. Just adding the file extensions fixed the issues for VTK and ITK but GDCM is doing something different, and I don't know what to do at this point.  I'm hoping maybe you or someone knows.

**Comment by malaterre** [comment]
OK, I see now what is happening. The patch is missing a call to `get_filename_component` to retrieve the actual test_name (TestVersion.cxx is the filename, but TestVersion is the actual test name).

**Comment by seanm** [comment]
@malaterre thanks!  I think I've fixed it now. Please review carefully, as I've changed parts I can't test.

**Pull request merged**
