### PR TITLE
GlobalInstance atomic & tautological warnings

### PR DESCRIPTION
**Pull request by seanm**
@malaterre

### CODE REVIEW

**Comment by malaterre** [comment]
@seanm gdcm.Global is a singleton, why would I make it "Also use C++11 std::atomic to make it all more thread safe." ?

**Comment by malaterre** [comment]
Unless this fixes something, I have to refuse this merge, GDCM is still geared toward c++98 unfortunately.

**Comment by seanm** [comment]
Ah, didn't realize you still support C++98...

If I remove the C++11 atomic stuff, would you accept the patch then?  i.e. the changes to remove  "static Global GlobalInstance" from the .h...

Then I can run Thread Sanitizer again and try to remember what I was trying to fix (I rediscovered this change in a working copy from months ago when updating ITK)... :)

**Comment by malaterre** [comment]
@seanm  OK let's do that, please resubmit a new PR.

**Comment by seanm** [comment]
OK, I'll try... though I always seem to have trouble using GitHub...

BTW: GDCM is technically already using C++11, it uses:
 - extern template
 - long long

:)

**Comment by seanm** [comment]
Meh, I can't figure out how to revise my commit, interactive rebase doesn't work, I think maybe because I've synced from upstream.

I guess I'll just destroy my fork and create it anew...

**Comment by malaterre** [comment]
@seanm I've removed the extern template stuff. That was a mistake. The `long long` case is interesting since it did not lead to warning and or errors so far.

**Comment by malaterre** [comment]
Closing this PR. Feel free to create a new one whenever you have time. Thanks

**Pull request closed without merging**
