### PR TITLE
COMP: Address warning due to undefined behavior.

### PR DESCRIPTION
**Pull request by DVigneault**
This patch addresses compiler warnings on OSx (Apple LLVM version 8.0.0 (clang-800.0.38)) concerning undefined behavior when shifting negative numbers:
````
warning: shifting a negative signed value is undefined [-Wshift-negative-value]
````

### CODE REVIEW

**Comment by DVigneault** [comment]
@malaterre Would you mind taking a look at this?

**Comment by malaterre** [comment]
Really I was starring at this patch and two things concerns me:

- I dont see why you changed the number of line for a simple `sed` replacement
- call me a purist, but I do not believe this code is correct for 1-complement, really the original writer wanted the compiler to do the right thing here. So I cannot accept a two-completement only patch, even if all machines are this way. I think `(int)(~0u)` would be better, but I need to think twice.

**Comment by DVigneault** [comment]
Thanks for the feedback!

- I changed the whitespace purely because I found it more readable.  I am of course happy to change it back.
- Another approach would be to hard code the values, as they've done in [this patch](https://github.com/richgel999/jpeg-compressor/pull/9/files).  In my opinion the intention is less clear, but at least there would be no question as to portability.

**Comment by malaterre** [comment]
Closing without merge. I've used: `s/-1/-1u/g` instead. As explained in the commit message, I believe the JPEG standard expects two's complement number representation anyway.

**Pull request closed without merging**
