### PR TITLE
Zlib 1.2.13

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@malaterre

**Comment by seanm** [comment]
@malaterre I noticed some errors on cdash: https://open.cdash.org/viewBuildError.php?buildid=8262754

I'm somewhat mystified by what is causing them... do you have access to that build bot?

**Comment by malaterre** [comment]
@seanm I've reverted your changes on release branch for now. It turns out that shared lib was also not supported on vs2019.

No rush to push newer zlib, I'll implement better CI for windows in the meantime.

**Comment by seanm** [comment]
@malaterre did you have a chance to improve your Windows CI?

**Pull request merged**
